### ISSUE TITLE
You Make a Great Helper

### ISSUE THREAD

**Issue by Drayr** [codecoding/PluralSightDownloader#51]
It seems that it is not creating the course folder, I do not know if it's an error, or not, testing now I'm finding great.
Two more question, if I change the page the download will stop, if not can I download several courses..

**Comment by robertohuertasm** [comment]
The app won't create a folder for each course. That's completely up to you.

If you change the page it won't stop downloading although you'll loose track of which clip is being downloaded as the treeview will probably be updated with new content. 

I would suggest you to not be greedy with the downloads as Pluralsight will otherwise cancel your account.

**Comment by Drayr** [comment]
Thanks for the tip.
